name: aurora_serverwrapper
description: Wrapper for minecraft server used with Aurora Launcher.
version: 0.1.0
homepage: https://aurora-team.ru

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  pedantic: ^1.9.0